### ISSUE TITLE
Fix Server logo avatar

### ISSUE THREAD

**Issue by LTSENG01** [LTSENG01/Discord-RoleBot#19]
https://github.com/LTSENG01/Discord-RoleBot/blob/774a53f24f416ae0a2f71c3473fbda11c60ea0a4/static/main.js#L16

**Comment by LTSENG01** [comment]
New image: `a_6d9390fadb6bc1fa5a59ede9cdfe26b6`

**Comment by LTSENG01** [comment]
Maybe also have the placeholder show up if it can't load the server image from Discord

**Comment by Aryan-Dang** [comment]
Your suggested comment worked.
So it's displaying the image now but could you clarify what's the placeholder you're referring to ?
